### ISSUE TITLE
Not Working in IE 10/11

### ISSUE THREAD

**Issue by enijar** [christinecha/choreographer-js#2]
First-off, brilliant work on this library. I like the API!

I've tested the [demo page](https://christinecha.github.io/choreographer-js/) and it doesn't work in IE 10/11.

Any future plans on making this cross-browser compliant?

**Comment by zhouzi** [comment]
@Enijar I am curious, what do you mean by the library doesn't work in IE10/11? Are there errors in the console? Are you able to scroll but the animation is not playing or the page is completely broken?

**Comment by christinecha** [comment]
Thanks @Enijar and @Zhouzi for checking it out!

I was using Array.from in a few places, which IE doesn't support, and it broke everything. Replaced across the board and it should be working now. 👍
