### ISSUE TITLE
Scale rgba alpha value?

### ISSUE THREAD

**Issue by RyanRoberts** [christinecha/choreographer-js#3]
Apologies if this is clear from the js itself.

Is it possible to scale the alpha value in an rgba color, for example:

```
{
  range: [-1, 600],
  selector: '#fixy',
  type: 'scale',
  style: 'background-color',
   from: "rgba(255,0,0,0)",
  to: "rgba(255,0,0,1)"
}
```

Obviously you can't scale a value like that but it should explain what I'm struggling to accomplish.

Thanks!

**Comment by christinecha** [comment]
Hey Ryan! You can only pass in single numerical values right now, but I'm going to add support for this soon. For now, I'd suggest creating a separate element to act as your background, fill it with color, and use `choreographer` to scale its opacity value instead.

**Comment by RyanRoberts** [comment]
Thanks for the response :)
