### ISSUE TITLE
Updating single animationConfig value

### ISSUE THREAD

**Issue by brandondurham** [christinecha/choreographer-js#4]
I have an animation that gets set up when my component mounts. I need to update the `from` value for the animation after a resize event. This is my initial config:

```
choreographer = new Choreographer({
    animations: [
        {
            range: [-1, 150],
            selector: '#licenseBar',
            type: 'scale',
            style: 'height',
            from: licenseBarExpandedHeight,
            to: licenseBarCollapsedHeight,
            unit: 'px'
        }
    ]
});
```

What’s the cleanest way to update the `from` value _after_ the animation has already been set up?

**Comment by christinecha** [comment]
Hey Brandon!

There's a method you can call named `Choreographer.updateAnimations()` that takes a new Animations array as its argument. And then, to avoid duplicating code, you might want to separate out the logic that returns the Animations array. So, maaaybe something like:

```
choreographer = new Choreographer({
    animations: getAnimations(licenseBarExpandedHeight)
});

window.addEventListener('resize', function() {
    choreographer.updateAnimations(getAnimations(newFromValue)) // to update animation values
    choreographer.runAnimationsAt(window.pageYOffset) // to re-trigger animation with new values
})

function getAnimations(fromValue) {
    return  [
        {
            range: [-1, 150],
            selector: '#licenseBar',
            type: 'scale',
            style: 'height',
            from: fromValue,
            to: licenseBarCollapsedHeight,
            unit: 'px'
        }
    ]
}
```

**Comment by brandondurham** [comment]
This is exactly what I ended up doing before I heard back. Good to know I was on the right track. Thanks for the response!
