### ISSUE TITLE
Thrown an error if placed before the body

### ISSUE THREAD

**Issue by abusedmedia** [christinecha/choreographer-js#7]
Thanks for this script. 
Just tested it quickly and found out an issue.

If the script src tag to import the library is placed before the ```body``` tag (for instance, the ```head``` tag) an undefined function error will be thrown at this line:
https://github.com/christinecha/choreographer-js/blob/master/src/getInjectedTransformString.js#L26

Best

**Comment by christinecha** [comment]
Yeah, you're going to want to import this after your related DOM elements or it's not going to work at all. Use it in a script tag at the end, right before the closing body tag, instead. 

Thanks for checking it out!
